var annotated_dup =
[
    [ "asgard", null, [
      [ "operators", "namespaceasgard_1_1operators.html", [
        [ "lenard_bernstein_collisions", "structasgard_1_1operators_1_1lenard__bernstein__collisions.html", "structasgard_1_1operators_1_1lenard__bernstein__collisions" ],
        [ "simple_bgk_collisions", "structasgard_1_1operators_1_1simple__bgk__collisions.html", "structasgard_1_1operators_1_1simple__bgk__collisions" ]
      ] ],
      [ "aux_field_entry", "structasgard_1_1aux__field__entry.html", "structasgard_1_1aux__field__entry" ],
      [ "boundary_flux", "classasgard_1_1boundary__flux.html", "classasgard_1_1boundary__flux" ],
      [ "dimension_id", "structasgard_1_1dimension__id.html", "structasgard_1_1dimension__id" ],
      [ "discretization_manager", "classasgard_1_1discretization__manager.html", "classasgard_1_1discretization__manager" ],
      [ "domain_range", "structasgard_1_1domain__range.html", "structasgard_1_1domain__range" ],
      [ "group_id", "structasgard_1_1group__id.html", "structasgard_1_1group__id" ],
      [ "h5manager", "classasgard_1_1h5manager.html", null ],
      [ "imex_explicit_group", "structasgard_1_1imex__explicit__group.html", "structasgard_1_1imex__explicit__group" ],
      [ "imex_implicit_group", "structasgard_1_1imex__implicit__group.html", "structasgard_1_1imex__implicit__group" ],
      [ "left_boundary_flux", "structasgard_1_1left__boundary__flux.html", "structasgard_1_1left__boundary__flux" ],
      [ "mass_md", "classasgard_1_1mass__md.html", "classasgard_1_1mass__md" ],
      [ "moment", "structasgard_1_1moment.html", "structasgard_1_1moment" ],
      [ "moment_id", "classasgard_1_1moment__id.html", "classasgard_1_1moment__id" ],
      [ "momentset", "classasgard_1_1momentset.html", "classasgard_1_1momentset" ],
      [ "momentset_gpu", "classasgard_1_1momentset__gpu.html", "classasgard_1_1momentset__gpu" ],
      [ "pde_domain", "classasgard_1_1pde__domain.html", "classasgard_1_1pde__domain" ],
      [ "pde_scheme", "classasgard_1_1pde__scheme.html", "classasgard_1_1pde__scheme" ],
      [ "position_dims", "structasgard_1_1position__dims.html", "structasgard_1_1position__dims" ],
      [ "prog_opts", "structasgard_1_1prog__opts.html", "structasgard_1_1prog__opts" ],
      [ "reconstruct_solution", "classasgard_1_1reconstruct__solution.html", "classasgard_1_1reconstruct__solution" ],
      [ "right_boundary_flux", "structasgard_1_1right__boundary__flux.html", "structasgard_1_1right__boundary__flux" ],
      [ "separable_func", "classasgard_1_1separable__func.html", "classasgard_1_1separable__func" ],
      [ "source", "structasgard_1_1source.html", "structasgard_1_1source" ],
      [ "sym_boundary_flux", "structasgard_1_1sym__boundary__flux.html", "structasgard_1_1sym__boundary__flux" ],
      [ "term_1d", "classasgard_1_1term__1d.html", "classasgard_1_1term__1d" ],
      [ "term_chain", "structasgard_1_1term__chain.html", null ],
      [ "term_div", "structasgard_1_1term__div.html", "structasgard_1_1term__div" ],
      [ "term_grad", "structasgard_1_1term__grad.html", "structasgard_1_1term__grad" ],
      [ "term_identity", "structasgard_1_1term__identity.html", null ],
      [ "term_interp", "structasgard_1_1term__interp.html", "structasgard_1_1term__interp" ],
      [ "term_lenard_bernstein_coll_theta", "structasgard_1_1term__lenard__bernstein__coll__theta.html", "structasgard_1_1term__lenard__bernstein__coll__theta" ],
      [ "term_manager", "structasgard_1_1term__manager.html", null ],
      [ "term_md", "classasgard_1_1term__md.html", "classasgard_1_1term__md" ],
      [ "term_moment_over_density", "structasgard_1_1term__moment__over__density.html", "structasgard_1_1term__moment__over__density" ],
      [ "term_penalty", "structasgard_1_1term__penalty.html", "structasgard_1_1term__penalty" ],
      [ "term_robin", "structasgard_1_1term__robin.html", "structasgard_1_1term__robin" ],
      [ "term_volume", "structasgard_1_1term__volume.html", "structasgard_1_1term__volume" ],
      [ "vector2d", "classasgard_1_1vector2d.html", "classasgard_1_1vector2d" ],
      [ "velocity_dims", "structasgard_1_1velocity__dims.html", "structasgard_1_1velocity__dims" ],
      [ "volume_electric", "structasgard_1_1volume__electric.html", "structasgard_1_1volume__electric" ]
    ] ]
];