from options import OUTPUT_DIR, HEADER_NAME, CPP_NAME
from fileio import get_mem_pdes, get_time_pdes
from mem_predictor import MemPredictor, MemPDE
from time_predictor import TimePredictor, TimePDE


with open(f'{OUTPUT_DIR}/{HEADER_NAME}', 'w') as cpp:
    cpp.write(
        '// Automatically generated by perf_predict\n#pragma once\n' +
        MemPredictor(get_mem_pdes()).to_cpp(header='pde.hpp') +
        TimePredictor(get_time_pdes()).to_cpp()
    )
